verify it's a file as well as being readable

diff --git a/system/function b/system/function
--- a/system/function
+++ b/system/function
@@ -53,9 +53,9 @@ calc() {
 # Code sourcer
 src() {
   if [ "x$VERBOSE_SOURCING" == "xtrue" ]; then
-    [ -r "$*" ] && { echo "Sourcing \"$*\"" && source "$*" && echo "Sourced \"$*\""; } || echo "Failed to source: \"$*\""
+    [ -f "$*" && -r "$*" ] && { echo "Sourcing \"$*\"" && source "$*" && echo "Sourced \"$*\""; } || echo "Failed to source: \"$*\""
   else
-    [ -r "$*" ] && source "$*"
+    [ -f "$*" && -r "$*" ] && source "$*"
   fi
 }
 
